#!/bin/python3

'''
Creates a json file (name formatted as '{set_id}.json') containing all cards printed in a given set in the directory this script is run.

Usage: ./get_json set_id
'''

# 2024.06.07, by @zachleach
import requests
import json
import time
import sys

set_id = sys.argv[1] if len(sys.argv) > 1 else None
search_expression = f"e:{set_id} order:set unique:prints"
url = "https://api.scryfall.com/cards/search"

data = []

while url:
    # make http request for json data
    response = requests.get(url, params={'q': search_expression})
    time.sleep(0.5)
    if response.status_code != 200:
        print(f"Error: {response.status_code}")
        break

    # extract page of json data and add to a list
    json_data = response.json()
    data += json_data['data']

    # get next page of data (if there is one)
    url = json_data.get('next_page')

with open(f'{set_id}.json', 'w') as file:
    json.dump(data, file, indent=4)
