#!/bin/python3

# 2024.06.07, by @zachleach

'''
add card data to a default dict with { 'layout': [card...] }
'''
for card_data in data:
    layout = card_data['layout']
    name = card_data['name']
    layouts[layout] += [name]
