#!/bin/python3

# 2024.06.07, by @zachleach
import json 
import ijson
import pprint
from collections import defaultdict

set_map = defaultdict(list)

with open("input.json", 'r') as file:
    json_iterable = ijson.items(file, 'item')
    card_iterator = (card_obj for card_obj in json_iterable)

    for card_data in card_iterator:
        set_id = card_data['set']
        set_map[set_id]

with open("input.json", 'r') as file:
    json_iterable = ijson.items(file, 'item')
    card_list = [card_obj for card_obj in json_iterable]

    pprint.pprint(card_list)





