#!/bin/python3

# https://requests.readthedocs.io/en/latest/
# https://scryfall.com/docs/api/cards/search

# 2024.06.03, by @zachleach
import requests
import json
import pprint
import time
from collections import defaultdict

expression = "e:mh3 order:set unique:prints"
url = "https://api.scryfall.com/cards/search"

data = []
layouts = defaultdict(list)

while url:
    # make http request for json data
    response = requests.get(url, params={'q': expression})
    time.sleep(0.5)
    if response.status_code != 200:
        print(f"Error: {response.status_code}")
        break

    # extract page of json data and add to a list
    json_data = response.json()
    data += json_data['data']

    # get next page of data (if there is one)
    url = json_data.get('next_page')




'''
for card_data in data:
    layout = card_data['layout']
    name = card_data['name']
    layouts[layout] += [name]
'''
