#!/bin/python3

# https://requests.readthedocs.io/en/latest/
# https://scryfall.com/docs/api/cards/search

# 2024.06.03, by @zachleach
import json
import pprint
import os
import sys


set_id = sys.argv[1] if len(sys.argv) > 1 else None
set_id = 'mh3'

data = []

with open(f'{set_id}.json', 'r') as file:
    data = json.load(file)



modal_dfc = None
for card_data in data:
    if card_data['layout'] == 'modal_dfc':
        modal_dfc = card_data
        break

'''
dict_keys(['normal', 'saga', 'prototype', 'adventure', 'transform', 'modal_dfc'])

'''
def get_png(card):
    layout = card['layout']
    if layout == 'modal_dfc'


def get_modal_dfc(card):


pprint.pprint(modal_dfc)




