#!/bin/python3

# 2024.06.07, by @zachleach
import requests
import json
import pprint
import os
import time

set_name = "mh3"
url = f"https://api.scryfall.com/cards/{set_name}"

i = 1; data = []
while url:
    response = requests.get(url + f'/{i}')
    if response.status_code == 404:
        break

    # extract page of json data and add to a list
    json_data = response.json()
    data += [json_data]
    pprint.pprint(data)

    # get next page of data (if there is one)
    time.sleep(0.5)
    i += 1

with open("mh3_522.json", "w") as file:
    json.dump(data, file, indent=4)

